version: '3.8'
services:
  mongodb:
    image: docker.io/mongodb/mongodb-community-server:latest
    restart: always
    ports:
      - "8090:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: utilisateur
      MONGO_INITDB_ROOT_PASSWORD: motdepasse
